In [1]:
import pandas as pd
import numpy as np

In [7]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
# Dimensiones del arreglo
a.shape

(3, 5)

In [10]:
# Número de dimensiones
a.ndim

2

In [12]:
# Tipo de las variables contenidas
a.dtype

dtype('int32')

In [13]:
# Número total de elementos, en todas las dimensiones
a.size

15

### Otros constructores

In [41]:
# Constructor estandar
b = np.array([1, 5.2, 7.0])
b

array([1. , 5.2, 7. ])

In [43]:
bp = np.array([[2, 4], [8, 9]])
bp

array([[2, 4],
       [8, 9]])

In [20]:
b.dtype

dtype('float64')

In [30]:
# Se puede forzar el tipo de las variables del ndarray
c = np.array([1, 2, 3], dtype=complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [34]:
# Constructor común de matriz de ceros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
# Constructor común de matriz de unos
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
# Constructor para la matriz identidad
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# Constructor de una matriz a partir de la diagonal
np.diag([1, 4, 5, np.pi])

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 4.        , 0.        , 0.        ],
       [0.        , 0.        , 5.        , 0.        ],
       [0.        , 0.        , 0.        , 3.14159265]])

#### Operaciones entre arreglos

In [49]:
# Escalar por un arreglo
7 * np.identity(4)

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [50]:
# Matrices auxiliares
A = np.array([[1, 2], [3, 4]])
B = np.array([[6, 7], [1, 2]])

In [48]:
# Producto elemento por elemento
A*B

array([[ 6, 14],
       [ 3,  8]])

In [51]:
A.dot(B)

array([[ 8, 11],
       [22, 29]])

In [74]:
# Vector renglón
v1 = np.array([[1, 2, 3]], dtype=float)
# Vector columna
v2 = v1.transpose() # v1.T es sinónimo
# Producto matricial, que coincide con el interno
v1.dot(v2)
# Para matrices complejas, se usa .conj().T

array([[14.]])

In [97]:
# Ejemplo de función vectorizada, para aplicar a escalares
def func(arg):
    return arg**2
#func([1, 2, 3]) <-- Esto no va a FUNCIONAR
l = np.vectorize(func)
l([1, 2, 3])

array([1, 4, 9])

## Pandas y Series

In [106]:
# Constructor más básico
pd.Series(l(np.arange(6)))

0     0
1     1
2     4
3     9
4    16
5    25
dtype: int32

In [102]:
# Constructor con índices
s1 = pd.Series([1, 2, 5], index=["a", "b", "c"], dtype=float)
s1

a    1.0
b    2.0
c    5.0
dtype: float64

In [104]:
# Acceder a los elementos como si fuera diccionario
s1["b"]

2.0

In [111]:
# Acceder a los elementos por índice
s1.iloc[1]

2.0

In [115]:
# Listas auxiliares
s2 = pd.Series([5, 3, 1], index=["a", "b", "c"], dtype=float)
s3 = pd.Series([1, 2, 5], index=["c", "d", "e"], dtype=float)

In [117]:
# Suma sobrecargada con las Series
s1 + 2

a    3.0
b    4.0
c    7.0
dtype: float64

In [118]:
# Producto sobrecargado con las Series
s1*2

a     2.0
b     4.0
c    10.0
dtype: float64

In [121]:
# Suma de Series
print(s1)
print(s2)
print(s1+s2)

a    1.0
b    2.0
c    5.0
dtype: float64
a    5.0
b    3.0
c    1.0
dtype: float64
a    6.0
b    5.0
c    6.0
dtype: float64


In [122]:
# Suma de Series con índices distintos
print(s1)
print(s3)
print(s1+s3)

a    1.0
b    2.0
c    5.0
dtype: float64
c    1.0
d    2.0
e    5.0
dtype: float64
a    NaN
b    NaN
c    6.0
d    NaN
e    NaN
dtype: float64


In [125]:
# Not a number, nunca son iguales
np.nan == np.nan

False

In [133]:
# Extracción por rangos
s1.iloc[:2]

a    1.0
b    2.0
dtype: float64

In [134]:
# Extracción por lista de índices
s1[["a", "c"]]

a    1.0
c    5.0
dtype: float64

In [135]:
# Operaciones entre pedazos de Series
s1 - s1[["a", "c"]]

a    0.0
b    NaN
c    0.0
dtype: float64

### Ahora sí, DataFrames

In [138]:
# Constructor básico
pd.DataFrame([[1, 2, 3], [3, 5, 6]])

0  1  2
0  1  2  3
1  3  5  6

In [141]:
# Constructor menos básico
pd.DataFrame([[1, 2, 3], [3, 5, 6]],index=["a", "z"],columns=["A", "B", "C"])

A  B  C
a  1  2  3
z  3  5  6

In [147]:
# definición por diccionario
df = pd.DataFrame({"A": s1, "B": s3})
df

A    B
a  1.0  NaN
b  2.0  NaN
c  5.0  1.0
d  NaN  2.0
e  NaN  5.0

In [150]:
# Sacar una columna por su nombre, como diccionario
df["A"]

a    1.0
b    2.0
c    5.0
d    NaN
e    NaN
Name: A, dtype: float64

In [153]:
# subdataframes por índices
df.loc["a", :]

A    1.0
B    NaN
Name: a, dtype: float64

In [155]:
# subdataframes por índices numéricos
df.iloc[[1, 3],[0,1]]

A    B
b  2.0  NaN
d  NaN  2.0